/*
 * CDC DUKKAN - ADMIN DATA MANAGEMENT
 * 
 * This file contains all the data for the CDC Dukkan website.
 * To update the website, use admin.html to generate new content
 * and paste it into this file, then push to GitHub.
 * 
 * DO NOT EDIT THIS FILE MANUALLY IF YOU ARE USING admin.html
 */

window.cdcData = {
    "currentMonth": "September 2025",
    "monthlyPayment": 5,
    "members": [
        {
            "name": "Ismail",
            "paid": true
        },
        {
            "name": "Basil",
            "paid": true
        }
    ],
    "bills": [
        {
            "id": 1,
            "amount": 7,
            "description": "Grocery Shopping",
            "date": "9/13/2025",
            "month": "September 2025"
        }
    ],
    "history": []
};

// This function is called by script.js to refresh the display
// after new data is loaded (e.g., after you update admin.js and refresh the main site)
if (typeof window.cdcDukkan !== 'undefined') {
    window.cdcDukkan.refreshData();
}

